site:
  title: "Social AI and Multi-Agent Systems | Nirav Ajmeri's Group at Bristol"
  description: "Welcome to Social AI and Multi-Agent Systems group at Bristol!"
  baseurl: ""
  url: "https://uob-mas.github.io"

collections:
  team:
    output: true
  publications:
    output: true
  projects:
    output: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

navigation:
  - title: Home
    url: /
  - title: Team
    url: /team/
  - title: Publications
    url: /publications/

